version: '3.4'

services:
  traefik-proxy:
    image: traefik:cantal
    restart: always
    command: 
      - --global.sendAnonymousUsage=false
      - --entrypoints.http.address=:80
      - --entrypoints.traefik.address=:8080
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=web
      - --providers.docker.swarmMode=false
    ports:
      - "80:80"
#      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
# 2.0-nál a command-ban beállítjuk azokat a dolgokat, amik előtte a toml-ben voltak
#      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=false"
      - "traefik.protocol=http"
    networks:
      - web

networks:
  web:
    external: true
